In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("ionosphere_data.csv")

In [3]:
data

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

In [4]:
data.isnull().any()

feature1     False
feature2     False
feature3     False
feature4     False
feature5     False
feature6     False
feature7     False
feature8     False
feature9     False
feature10    False
feature11    False
feature12    False
feature13    False
feature14    False
feature15    False
feature16    False
feature17    False
feature18    False
feature19    False
feature20    False
feature21    False
feature22    False
feature23    False
feature24    False
feature25    False
feature26    False
feature27    False
feature28    False
feature29    False
feature30    False
feature31    False
feature32    False
feature33    False
feature34    False
label        False
dtype: bool

In [5]:
data.isnull()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
347,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
348,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
349,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
350,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
train = data.sample(frac=0.6, random_state=0)
train

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
6,1,0,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,...,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975,g
52,1,0,1.00000,1.00000,1.00000,1.00000,0.91010,1.00000,-0.26970,1.00000,...,-1.00000,1.00000,-1.00000,1.00000,-1.00000,1.00000,-0.34686,1.00000,0.34845,g
114,1,0,0.91353,0.81586,-0.72973,1.00000,-0.39466,0.55735,0.05405,0.29730,...,0.00002,-0.00001,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,b
45,0,0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,...,-1.00000,-1.00000,-1.00000,-1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,b
106,1,0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,1.00000,0.10976,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,1,0,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,...,0.00000,1.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,b
269,1,0,0.84843,0.06794,0.80562,-0.02299,0.77031,-0.03299,0.66725,-0.06620,...,-0.22822,0.48659,-0.09128,0.52613,-0.08537,0.44277,-0.09621,0.42223,-0.09808,g
226,0,0,0.00000,0.00000,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,...,0.00000,1.00000,1.00000,0.00000,0.00000,-1.00000,1.00000,0.00000,0.00000,b
327,1,0,1.00000,1.00000,0.36700,0.06158,0.12993,0.92713,-0.27586,0.93596,...,-0.45950,0.85471,-0.06831,1.00000,1.00000,0.38670,0.00246,0.17758,0.79790,g
40,1,0,1.00000,0.06538,1.00000,0.20746,1.00000,0.26281,0.93051,0.32213,...,0.72082,0.27712,0.72386,0.19296,0.70682,0.11372,0.72688,0.06990,0.71444,g

In [7]:
test = data.drop(train.index)

In [8]:
test.shape

(140, 35)

In [9]:
 x_train = train.drop(columns=['label'])

In [10]:
y_train = train['label']

In [11]:
x_test = test.drop(columns=['label'])

In [12]:
y_test = test['label']

In [13]:
y_train = pd.Series(map(lambda x: dict(g=1, b=0)[x],
              y_train.values.tolist()), y_train.index)

In [14]:
y_test=pd.Series(map(lambda x: dict(g=1, b=0)[x],
              y_test.values.tolist()), y_test.index)

In [15]:
import keras 
import tensorflow as tf

Using TensorFlow backend.
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\DELL\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [16]:
mean = x_train.mean()
x_train -= mean
std = x_train.std()
x_train /= std
x_test /= std

In [21]:
x_train

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
6,0.398228,NaN,0.711189,-0.357651,0.707334,-0.684032,0.819808,-0.796770,0.726989,-0.937131,...,-0.203425,-1.430374,-0.710643,-1.337274,-0.474029,-1.689331,-0.527130,-1.564129,-0.763433,-1.717579
52,0.398228,NaN,0.759751,2.088719,0.804677,1.872312,0.786296,1.576169,-1.380385,1.660203,...,0.926010,-1.788778,0.875330,-1.647125,1.144714,-2.040839,1.205471,-0.660003,1.316833,0.720112
114,0.398228,NaN,0.585657,1.681426,-2.313991,1.872312,-1.648320,0.757796,-0.776432,0.226940,...,-0.586416,0.162713,-0.961560,0.124465,-0.552188,-0.044200,-0.456305,0.012508,-0.510655,-0.013279
45,-2.499224,NaN,-1.253592,-0.123149,-0.998302,-0.243866,-0.911904,-0.272634,0.988233,1.660203,...,-2.266521,-1.788778,-2.798412,-1.647125,-2.249090,1.952440,1.205471,0.012508,-0.510655,-0.013279
106,0.398228,NaN,-1.253592,-0.123149,-0.998302,-0.243866,-0.911904,-0.272634,-0.877261,-0.379449,...,-0.586366,0.162674,0.875330,0.318915,-0.552188,-0.044200,-0.456305,0.012508,-0.510655,-0.013279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,0.398228,NaN,-1.253592,-0.123149,-0.998302,-0.243866,-0.911904,-0.272634,-0.877261,-0.379449,...,-0.586366,0.162674,0.875330,1.896056,-0.552188,-0.044200,-0.456305,0.012508,-0.510655,-0.013279
269,0.398228,NaN,0.454589,0.027125,0.454214,-0.292517,0.525455,-0.333626,0.367490,-0.514474,...,0.203946,-0.282686,-0.067738,-0.037245,0.340603,-0.214653,0.279479,-0.174029,0.260965,-0.219711
226,-2.499224,NaN,-1.253592,-0.123149,0.804677,1.872312,0.954045,1.576169,-0.877261,-0.379449,...,-0.586366,0.162674,0.875330,1.896056,-0.552188,-0.044200,-2.118082,1.951361,-0.510655,-0.013279
327,0.398228,NaN,0.759751,2.088719,-0.336609,-0.113552,-0.669462,1.441447,-1.391877,1.529584,...,0.653455,-0.734018,0.608451,0.003448,1.144714,1.952440,0.186303,0.017277,-0.186129,1.666080
40,0.398228,NaN,0.759751,0.021463,0.804677,0.195156,0.954045,0.213250,0.858600,0.277584,...,-0.008661,1.569320,-0.452508,1.406849,-0.224754,1.367065,-0.267328,1.421822,-0.382913,1.490419

In [17]:
y_train

6      1
52     1
114    0
45     0
106    0
      ..
246    0
269    1
226    0
327    1
40     1
Length: 211, dtype: int64

In [18]:
from keras import layers
from keras import models
def build_model():
    model = models.Sequential([
        layers.Dense(16, activation='tanh', input_shape = (x_train.shape[1],)),
        layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
    return model

In [19]:
model = build_model()

WARNING:tensorflow:From C:\Users\DELL\anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [20]:
model.fit(x_train, y_train, epochs=100)

WARNING:tensorflow:From C:\Users\DELL\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Epoch 1/100
211/211 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.0000e+00
Epoch 2/100
211/211 [==============================] - 0s 152us/step - loss: nan - accuracy: 0.0000e+00
Epoch 3/100
211/211 [==============================] - 0s 161us/step - loss: nan - accuracy: 0.0000e+00
Epoch 4/100
211/211 [==============================] - 0s 175us/step - loss: nan - accuracy: 0.0000e+00
Epoch 5/100
211/211 [==============================] - 0s 156us/step - loss: nan - accuracy: 0.0000e+00
Epoch 6/100
211/211 [==============================] - 0s 147us/step - loss: nan - accuracy: 0.0000e+00
Epoch 7/100
211/211 [==============================] - 0s 166us/step - loss: nan - accuracy: 0.0000e+00
Epoch 8/100
211/211 [==============================] - 0s 175us/step - loss: nan - accuracy: 0.0000e+00
Epoch 9/100
211/211 [==============================] - 0s 171us/step - loss: nan - accuracy: 0.0000e+00
Epoch 10/100
211/211 [==============================] - 0s 157us/step - loss: nan - accuracy: 0.0000e+00
Epoch 11/100
211/211 [==============================] - 0s 138us/step - loss: nan - accuracy: 0.0000e+00
Epoch 12/100
211/211 [==============================] - 0s 147us/step - loss: nan - accuracy: 0.0000e+00
Epoch 13/100
211/211 [==============================] - 0s 147us/step - loss: nan - accuracy: 0.0000e+00
Epoch 14/100
211/211 [==============================] - 0s 180us/step - loss: nan - accuracy: 0.0000e+00
Epoch 15/100
211/211 [==============================] - 0s 156us/step - loss: nan - accuracy: 0.0000e+00
Epoch 16/100
211/211 [==============================] - 0s 142us/step - loss: nan - accuracy: 0.0000e+00
Epoch 17/100
211/211 [==============================] - 0s 161us/step - loss: nan - accuracy: 0.0000e+00
Epoch 18/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 19/100
211/211 [==============================] - 0s 152us/step - loss: nan - accuracy: 0.0000e+00
Epoch 20/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 21/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 22/100
211/211 [==============================] - 0s 142us/step - loss: nan - accuracy: 0.0000e+00
Epoch 23/100
211/211 [==============================] - 0s 166us/step - loss: nan - accuracy: 0.0000e+00
Epoch 24/100
211/211 [==============================] - 0s 157us/step - loss: nan - accuracy: 0.0000e+00
Epoch 25/100
211/211 [==============================] - 0s 171us/step - loss: nan - accuracy: 0.0000e+00
Epoch 26/100
211/211 [==============================] - 0s 157us/step - loss: nan - accuracy: 0.0000e+00
Epoch 27/100
211/211 [==============================] - 0s 157us/step - loss: nan - accuracy: 0.0000e+00
Epoch 28/100
211/211 [==============================] - 0s 171us/step - loss: nan - accuracy: 0.0000e+00
Epoch 29/100
211/211 [==============================] - 0s 138us/step - loss: nan - accuracy: 0.0000e+00
Epoch 30/100
211/211 [==============================] - 0s 175us/step - loss: nan - accuracy: 0.0000e+00
Epoch 31/100
211/211 [==============================] - 0s 147us/step - loss: nan - accuracy: 0.0000e+00
Epoch 32/100
211/211 [==============================] - 0s 161us/step - loss: nan - accuracy: 0.0000e+00
Epoch 33/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 34/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 35/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 36/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 37/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 38/100
211/211 [==============================] - 0s 138us/step - loss: nan - accuracy: 0.0000e+00
Epoch 39/100
211/211 [==============================] - 0s 104us/step - loss: nan - accuracy: 0.0000e+00
Epoch 40/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 41/100
211/211 [==============================] - 0s 147us/step - loss: nan - accuracy: 0.0000e+00
Epoch 42/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 43/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 44/100
211/211 [==============================] - 0s 142us/step - loss: nan - accuracy: 0.0000e+00
Epoch 45/100
211/211 [==============================] - 0s 95us/step - loss: nan - accuracy: 0.0000e+00
Epoch 46/100
211/211 [==============================] - 0s 138us/step - loss: nan - accuracy: 0.0000e+00
Epoch 47/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 48/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 49/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 50/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 51/100
211/211 [==============================] - 0s 104us/step - loss: nan - accuracy: 0.0000e+00
Epoch 52/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 53/100
211/211 [==============================] - 0s 104us/step - loss: nan - accuracy: 0.0000e+00
Epoch 54/100
211/211 [==============================] - 0s 133us/step - loss: nan - accuracy: 0.0000e+00
Epoch 55/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 56/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 57/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 58/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 59/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 60/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 61/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 62/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 63/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 64/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 65/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 66/100
211/211 [==============================] - 0s 95us/step - loss: nan - accuracy: 0.0000e+00
Epoch 67/100
211/211 [==============================] - 0s 133us/step - loss: nan - accuracy: 0.0000e+00
Epoch 68/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 69/100
211/211 [==============================] - 0s 104us/step - loss: nan - accuracy: 0.0000e+00
Epoch 70/100
211/211 [==============================] - ETA: 0s - loss: nan - accuracy: 0.0000e+0 - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 71/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 72/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 73/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 74/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 75/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 76/100

211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 77/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 78/100
211/211 [==============================] - 0s 104us/step - loss: nan - accuracy: 0.0000e+00
Epoch 79/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 80/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 81/100
211/211 [==============================] - 0s 142us/step - loss: nan - accuracy: 0.0000e+00
Epoch 82/100
211/211 [==============================] - 0s 133us/step - loss: nan - accuracy: 0.0000e+00
Epoch 83/100
211/211 [==============================] - 0s 147us/step - loss: nan - accuracy: 0.0000e+00
Epoch 84/100
211/211 [==============================] - 0s 138us/step - loss: nan - accuracy: 0.0000e+00
Epoch 85/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 86/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 87/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 88/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 89/100
211/211 [==============================] - 0s 133us/step - loss: nan - accuracy: 0.0000e+00
Epoch 90/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 91/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 92/100
211/211 [==============================] - 0s 133us/step - loss: nan - accuracy: 0.0000e+00
Epoch 93/100
211/211 [==============================] - 0s 128us/step - loss: nan - accuracy: 0.0000e+00
Epoch 94/100
211/211 [==============================] - 0s 100us/step - loss: nan - accuracy: 0.0000e+00
Epoch 95/100
211/211 [==============================] - 0s 109us/step - loss: nan - accuracy: 0.0000e+00
Epoch 96/100
211/211 [==============================] - 0s 114us/step - loss: nan - accuracy: 0.0000e+00
Epoch 97/100
211/211 [==============================] - 0s 123us/step - loss: nan - accuracy: 0.0000e+00
Epoch 98/100
211/211 [==============================] - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 99/100
211/211 [==============================] - ETA: 0s - loss: nan - accuracy: 0.0000e+0 - 0s 119us/step - loss: nan - accuracy: 0.0000e+00
Epoch 100/100
211/211 [==============================] - ETA: 0s - loss: nan - accuracy: 0.0000e+0 - 0s 114us/step - loss: nan - accuracy: 0.0000e+00

In [100]:
model.evaluate(x_test, y_test, verbose=1)

140/140 [==============================] - 0s 772us/step

[0.3263555780053139, 0.8428571224212646]

In [101]:
prediction = model.predict(x_test)

In [102]:
prediction[-1]

array([0.9587351], dtype=float32)

In [103]:
prediction.shape

(140, 1)

In [104]:
y_test

0      1
2      1
3      0
9      0
10     1
      ..
336    1
338    1
344    1
346    1
349    1
Length: 140, dtype: int64

In [105]:
np.sum(prediction[1]).round()

1.0

In [106]:
np.argmax(prediction[1])

0

In [115]:
x = (x_train.shape[1],)

In [116]:
from sklearn.preprocessing import MinMaxScaler

In [119]:
scalar = MinMaxScaler()
scalar.fit(x_test)
test = scalar.transform(x_test)

In [108]:
ynew = model.predict_classes(x)

(34,)

In [121]:
print("x_train=%s, Predicted=%s" % (test[0], y_test[0]))

x_train=[1.       0.       0.997695 0.470555 0.926215 0.51153  0.91699  0.31146
 1.       0.5188   0.926215 0.411225 0.798775 0.275275 0.80268  0.308885
 0.92178  0.30729  0.79106  0.33904  0.784855 0.35163  0.68473  0.263215
 0.784055 0.244145 0.70539  0.26916  0.60633  0.32955  0.711335 0.227565
 0.593205 0.2735  ], Predicted=1

In [111]:
# PREDICTED_CLASSES = prediction
# temp = (sum(y_test == PREDICTED_CLASSES))
# temp/len(y_test)